version: "3.9"

services:
  postgres:
    image: postgres:16
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports: ["5432:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]
